steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - australia-southeast1-docker.pkg.dev/$PROJECT_ID/lightbearer-sim/app:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - australia-southeast1-docker.pkg.dev/$PROJECT_ID/lightbearer-sim/app:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - lightbearer-sim
      - --image=australia-southeast1-docker.pkg.dev/$PROJECT_ID/lightbearer-sim/app:$COMMIT_SHA
      - --region=australia-southeast1
      - --platform=managed
      - --allow-unauthenticated
      - --project=$PROJECT_ID

options:
  logging: CLOUD_LOGGING_ONLY
